# Generated by Django 6.0.6 on 2026-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
